### ISSUE TITLE
[BUG] - Incomplete Report Generation in AgenticJS

### ISSUE THREAD

**Issue by dannleft** [AI-Champions/AgenticJS#24]
### Describe the Bug
The issue arises when generating reports through agents that involve a search and analysis of information. The resulting report is often incomplete or truncated, appearing as if it has not fully formed. This truncation disrupts the integrity and utility of the report.

### AgenticJS Team Config
Not available 

### Steps to Reproduce
1. Navigate to the provided playground link.
2. Initiate the data search and analysis task using the configured agents.
3. Observe the output where the report generation should occur.
4. Notice that the report ends abruptly and appears incomplete.

![image](https://github.com/user-attachments/assets/affbf0b4-e1c7-40f2-ad4e-b00ba241de98)
![image](https://github.com/user-attachments/assets/c462f755-a80c-43f0-8095-fff1dc4348cd)

### Current vs. Expected behavior
**Current Behavior:** When the report is generated after performing a search and analysis, it cuts off partway through without displaying the full content. 

**Expected Behavior:** The report should fully render all the analyzed data and conclusions based on the search criteria, providing a complete and comprehensive overview.

### Environment
- Framework/Library: AgenticJS Playground
- AgenticJS Version: 0.0.21
- JavaScript Runtime: Chrome Version 89

**Comment by OdinSweng** [comment]
Thank you, @dannleft. Let's review it and fix it

**Comment by OdinSweng** [comment]
@dannleft thank you for reporting this issue. I attempted to reproduce the problem, but I could not observe the behavior as described.

To ensure that the result is fully rendered, I recommend verifying the final output of the workflow. You can temporarily monitor the output by checking the browser console
<img width="1885" alt="Screenshot 2024-08-28 at 3 12 28 PM" src="https://github.com/user-attachments/assets/3e56b309-68d3-4473-8121-cd532db1cb48">
However, this is a temporary solution, as console logging may be removed in future updates.

For a more reliable approach, I suggest using the Redux DevTools extension, which will allow you to track the actions and state changes within the application <img width="1909" alt="Screenshot 2024-08-28 at 3 13 06 PM" src="https://github.com/user-attachments/assets/e092d5af-864d-4348-850f-7fa3176e89ab">
You can download the extension here: [Redux DevTools Extension](https://chromewebstore.google.com/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en).

If you encounter the issue again and verify that the result is indeed incomplete, please use the "Share" option in the playground to share the specific team setup where the problem occurs (e.g., https://www.agenticjs.com/share/XNprxOB3Og233P9h05nu). This will help us investigate further.

**Comment by dannleft** [comment]
Thank you @OdinSweng . This actually happened about a month and a half ago, and it hasn't happened to me since then. In the screenshots I shared, you can see that the report was not complete when it was generated. But as I mentioned, it was something that happened a month and a half ago.
