### ISSUE TITLE
[DOC ISSUE] - Incorrect URLs in Core Concepts: Tools Section

### ISSUE THREAD

**Issue by dannleft** [AI-Champions/AgenticJS#25]
### Describe the Issue
In the documentation section **'Core Concepts: Tools'**, the URLs for the tools (Tavily Search, Dall-E Tool, Discord Tool, Google Calendar Tool, WolframAlpha Tool) contain an incorrect **'#' symbol**, which makes the links non-functional. This error prevents users from accessing the linked resources directly from the documentation page.

### Doc URL
[AgenticJS Documentation - Core Concepts: Tools](https://docs.agenticjs.com/core-concepts/Tools)

### Expected Behavior
Clicking on the tool links should redirect to the respective tool's page or documentation, allowing users to learn more about these integrations.

### Screenshots

![image](https://github.com/user-attachments/assets/ac2e66c1-4857-48a4-ac06-bd7542f73d77)

**Comment by dannleft** [comment]
The correction has been applied and we are waiting for the changes to be confirmed.

**Comment by darielnoel** [comment]
Done -> https://github.com/AI-Champions/agenticjs-docs/pull/2
