### ISSUE TITLE
[BUG] - Playground Preview Does Not Update When Using Promise in Example Code

### ISSUE THREAD

**Issue by dannleft** [AI-Champions/AgenticJS#50]
### Describe the Bug
When attempting to modify code using the example codes provided in the AgenticJS documentation on their website, the playground preview does not update correctly. The issue seems to stem from the example code ending with:

```javascript
team.start().then((result) => {
  console.log("Final Output:", result);
});
```

This promise handling appears to interfere with the playground’s live preview functionality.

### AgenticJS Team Config
To reproduce the issue, you can use the following link to an AgenticJS playground setup with an example configuration: [Example Playground](https://docs.agenticjs.com/get-started/Example%20Trip%20Planning)

### Steps to Reproduce
1. Open the [Example Playground](https://www.agenticjs.com/) provided.
2. Modify any part of the example code. 
3. Observe that the preview of the result does not update after making the modification.

### Current vs. Expected behavior
**Current Behavior**: After modifying the code and running `team.start().then((result) => { console.log("Final Output:", result); });`, the preview fails to show the updated results.

<img width="639" alt="image" src="https://github.com/user-attachments/assets/9ecfa8b0-1624-4373-89c4-a65ef651634e">

**Expected Behavior**: Modifying the code in the playground should immediately update the preview upon executing `team.start();` without needing to handle the promise.

### Environment
- Framework/Library: JavaScript / AgenticJS
- AgenticJS Version: 0.1.0
- JavaScript Runtime: Chrome

**Comment by OdinSweng** [comment]
@dannleft thank you for bringing this issue to our attention. I'm happy to inform you that the problem has been resolved.

To clarify, in the playground, it is not necessary to include `team.start();`. Simply defining and creating the team is sufficient for the playground's live preview to function correctly.

**Comment by dannleft** [comment]
Thanks for the quick response @OdinSweng . Great then 🚀
